networks:
  app-network:
    driver: bridge

# Определяем том для данных MySQL
volumes:
  mysql_data:


services:
  # 1. Сервис Базы данных
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www

    networks:
      - app-network
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: unless-stopped
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules

    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
